/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FrontiersRouteImport } from './routes/frontiers'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as RouteRouteIdRouteImport } from './routes/route.$routeId'
import { Route as ApiPublicV1BestRouteImport } from './routes/api/public/v1/best'
import { Route as ApiPublicV1ModelsRouteImport } from './routes/api/public/v1/models'
import { Route as ApiPublicV1RoutesRouteImport } from './routes/api/public/v1/routes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontiersRoute = FrontiersRouteImport.update({
  id: '/frontiers',
  path: '/frontiers',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRouteIdRoute = RouteRouteIdRouteImport.update({
  id: '/route/$routeId',
  path: '/route/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BestRoute = ApiPublicV1BestRouteImport.update({
  id: '/api/public/v1/best',
  path: '/api/public/v1/best',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ModelsRoute = ApiPublicV1ModelsRouteImport.update({
  id: '/api/public/v1/models',
  path: '/api/public/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RoutesRoute = ApiPublicV1RoutesRouteImport.update({
  id: '/api/public/v1/routes',
  path: '/api/public/v1/routes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/frontiers': typeof FrontiersRoute
  '/methodology': typeof MethodologyRoute
  '/route/$routeId': typeof RouteRouteIdRoute
  '/api/public/v1/best': typeof ApiPublicV1BestRoute
  '/api/public/v1/models': typeof ApiPublicV1ModelsRoute
  '/api/public/v1/routes': typeof ApiPublicV1RoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/frontiers': typeof FrontiersRoute
  '/methodology': typeof MethodologyRoute
  '/route/$routeId': typeof RouteRouteIdRoute
  '/api/public/v1/best': typeof ApiPublicV1BestRoute
  '/api/public/v1/models': typeof ApiPublicV1ModelsRoute
  '/api/public/v1/routes': typeof ApiPublicV1RoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/frontiers': typeof FrontiersRoute
  '/methodology': typeof MethodologyRoute
  '/route/$routeId': typeof RouteRouteIdRoute
  '/api/public/v1/best': typeof ApiPublicV1BestRoute
  '/api/public/v1/models': typeof ApiPublicV1ModelsRoute
  '/api/public/v1/routes': typeof ApiPublicV1RoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/frontiers'
    | '/methodology'
    | '/route/$routeId'
    | '/api/public/v1/best'
    | '/api/public/v1/models'
    | '/api/public/v1/routes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/frontiers'
    | '/methodology'
    | '/route/$routeId'
    | '/api/public/v1/best'
    | '/api/public/v1/models'
    | '/api/public/v1/routes'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/frontiers'
    | '/methodology'
    | '/route/$routeId'
    | '/api/public/v1/best'
    | '/api/public/v1/models'
    | '/api/public/v1/routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  FrontiersRoute: typeof FrontiersRoute
  MethodologyRoute: typeof MethodologyRoute
  RouteRouteIdRoute: typeof RouteRouteIdRoute
  ApiPublicV1BestRoute: typeof ApiPublicV1BestRoute
  ApiPublicV1ModelsRoute: typeof ApiPublicV1ModelsRoute
  ApiPublicV1RoutesRoute: typeof ApiPublicV1RoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontiers': {
      id: '/frontiers'
      path: '/frontiers'
      fullPath: '/frontiers'
      preLoaderRoute: typeof FrontiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/$routeId': {
      id: '/route/$routeId'
      path: '/route/$routeId'
      fullPath: '/route/$routeId'
      preLoaderRoute: typeof RouteRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/best': {
      id: '/api/public/v1/best'
      path: '/api/public/v1/best'
      fullPath: '/api/public/v1/best'
      preLoaderRoute: typeof ApiPublicV1BestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/models': {
      id: '/api/public/v1/models'
      path: '/api/public/v1/models'
      fullPath: '/api/public/v1/models'
      preLoaderRoute: typeof ApiPublicV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/routes': {
      id: '/api/public/v1/routes'
      path: '/api/public/v1/routes'
      fullPath: '/api/public/v1/routes'
      preLoaderRoute: typeof ApiPublicV1RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  FrontiersRoute: FrontiersRoute,
  MethodologyRoute: MethodologyRoute,
  RouteRouteIdRoute: RouteRouteIdRoute,
  ApiPublicV1BestRoute: ApiPublicV1BestRoute,
  ApiPublicV1ModelsRoute: ApiPublicV1ModelsRoute,
  ApiPublicV1RoutesRoute: ApiPublicV1RoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
